# Generated by Django 4.2.1 on 2023-05-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_n_air", "0002_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
