# Generated by Django 4.2.1 on 2023-05-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("first_n_air", "0003_alter_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sneakers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("Character", models.TextField()),
                (
                    "price_type",
                    models.CharField(
                        choices=[("so'm", "so'm"), ("rubl", "rubl"), ("$", "$")],
                        default="so'm",
                        max_length=10,
                    ),
                ),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="")),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="first_n_air.category",
                    ),
                ),
            ],
        ),
    ]
